from typing import Optional
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field

from services.preprocessing import preprocess_image
from services.classifier import predict_species

app = FastAPI(
    title="PlantGuardian AI Microservice",
    description="Stateless Computer Vision & Classification Service for PlantGuardian",
    version="1.0.0",
)


class ClassifyRequest(BaseModel):
    image_base64: str = Field(..., description="Base64 encoded string of image frame")
    request_id: Optional[str] = Field(None, description="Tracking UUID generated by Laravel")


@app.get("/health")
def health_check():
    return {"status": "ok", "service": "PlantGuardian AI Service"}


@app.post("/classify")
def classify_plant(payload: ClassifyRequest):
    if not payload.image_base64:
        return {
            "success": False,
            "reason": "empty_image_data",
        }

    try:
        processed_image = preprocess_image(payload.image_base64)
    except Exception as e:
        return {
            "success": False,
            "reason": "invalid_image_data",
            "detail": str(e),
        }

    success, result = predict_species(processed_image)

    return result
